services:
  todo:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8099:8080"
    volumes:
      - '.:/app'
    depends_on:
      - todo_db
  todo_db:
    image: postgres:15.3
    volumes:
      - db:/var/lib/postgresql/data
      - ./docker/db:/home/db
    environment:
        - POSTGRES_USER=db
        - POSTGRES_PASSWORD=db
        - POSTGRES_DB=db
    ports:
      - "54322:5432"
    networks:
      - default
volumes:
  db: